name: Codacy Analysis CLI

on:
  push:
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: "./Source"
      - name: Display Abbreviations  
        run: |
          echo LOC - Lines of Code
          echo CLOC - Commented Lines of Code
          echo CC - Cyclomatic Complexity
          echo #methods - Number of Methods
          echo #classes - Number of Classes
