name: Code Quality/Unit Tests

on:
  push:
    branches-ignore:
      - main
      - docs
  pull_request:
    branches:
      - main

jobs:
  Run-Jest:
    name: Run Tests/Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo npm install -g jest
    - run: npm test
    - run: npm coverage
