name: Lint Code Base

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: 
      - main
    types: [opened]

  # Can be triggered manually on Actions section on GitHub
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Lints through entire code base for syntax/style errors
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Set which file types to lint and what folders/files to exclude
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          FILTER_REGEX_EXCLUDE: .*/JSDocumentation/.*
