name: Lint Code Base

# Run for PRs and ignore merges and documentation
on:
  push:
    branches-ignore:
      - main
      - gh-pages

  # Can be triggered manually on Actions section on GitHub
  workflow_dispatch:

jobs:
  run-tests:
    name: Lint Code Base Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run Jest and Cypress to automatically run tests and show code coverage
      - name: Run Eslint, Stylelint, Htmlhint
        run: | 
              npm i # Handle installation on virtual machine
              npm run lint_test # Run linter tests and output results
